ports:
- port: 8000
  onOpen: open-preview
- port: 8888
  onOpen: ignore
tasks:
- before: npm install netlify-cli -g
  init: yarn && yarn build
  command: netlify dev --live
- init: cd plugins/gatsby-remark-gitpod && npm install
  openMode: split-right
